### ISSUE TITLE
Routes Look Ugly

### ISSUE THREAD

**Issue by mehradsadeghi** [imanghafoori1/laravel-tasks#4]
Is there any particular reason you haven't used `Auth::routes()` in this part of routes ?
https://github.com/imanghafoori1/laravel-tasks/blob/4cbda161774c627f7ee55e2b050e889cc5969738/routes/web.php#L10-L28

**Comment by imanghafoori1** [comment]
No it is not ugly. it is explicit.
yes there is a reason.
