### ISSUE TITLE
Route [tasks.index] not defined

### ISSUE THREAD

**Issue by FelipeVeiga** [imanghafoori1/laravel-tasks#8]
Hello there,
how can i fix it ?

Route [tasks.index] not defined

**Comment by imanghafoori1** [comment]
please leave an screenshot of what you see

**Comment by FelipeVeiga** [comment]
hmmm 
![image](https://user-images.githubusercontent.com/32652877/107836420-d8c31280-6d7b-11eb-8511-8ed4f48f6fe6.png)

**Comment by FelipeVeiga** [comment]
`PS C:\Users\Felipe\Desktop\Projetos\testes\task-example\laravel-tasks> php artisan route:list
+--------+----------+-------------------------------+------------------------------+-----------------------------------------------------------------------------------+--------------+
| Domain | Method   | URI                           | Name                         | Action                                                                            | Middleware   |
+--------+----------+-------------------------------+------------------------------+-----------------------------------------------------------------------------------+--------------+
|        | GET|HEAD | /                             | welcome                      | Illuminate\Routing\ViewController                                                 | web          |
|        | POST     | email/resend                  | verification.resend          | App\Http\Controllers\Auth\VerificationController@resend                           | web          |
|        |          |                               |                              |                                                                                   | auth         |
|        |          |                               |                              |                                                                                   | throttle:6,1 |
|        | GET|HEAD | email/verify                  | verification.notice          | App\Http\Controllers\Auth\VerificationController@show                             | web          |
|        |          |                               |                              |                                                                                   | auth         |
|        | GET|HEAD | email/verify/{id}/{hash}      | verification.verify          | App\Http\Controllers\Auth\VerificationController@verify                           | web          |
|        |          |                               |                              |                                                                                   | auth         |
|        |          |                               |                              |                                                                                   | signed       |
|        |          |                               |                              |                                                                                   | throttle:6,1 |
|        | GET|HEAD | login                         | login                        | App\Http\Controllers\Auth\LoginController@showLoginForm                           | web          |
|        |          |                               |                              |                                                                                   | guest        |
|        | POST     | login                         | login.post                   | App\Http\Controllers\Auth\LoginController@login                                   | web          |
|        |          |                               |                              |                                                                                   | guest        |
|        | GET|HEAD | logout                        | logout                       | App\Http\Controllers\Auth\LoginController@logout                                  | web          |
|        |          |                               |                              |                                                                                   | auth         |
|        | GET|HEAD | password/confirm              | password.confirm             | App\Http\Controllers\Auth\ConfirmPasswordController@showConfirmForm               | web          |
|        |          |                               |                              |                                                                                   | auth         |
|        | POST     | password/confirm              |                              | App\Http\Controllers\Auth\ConfirmPasswordController@confirm                       | web          |
|        |          |                               |                              |                                                                                   | auth         |
|        | POST     | password/email                | password.email               | App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail             | web          |
|        |          |                               |                              |                                                                                   | guest        |
|        | GET|HEAD | password/reset                | password.request             | App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm            | web          |
|        |          |                               |                              |                                                                                   | guest        |
|        | POST     | password/reset                | password.update              | App\Http\Controllers\Auth\ResetPasswordController@reset                           | web          |
|        |          |                               |                              |                                                                                   | guest        |
|        | GET|HEAD | password/reset/{token}        | password.reset               | App\Http\Controllers\Auth\ResetPasswordController@showResetForm                   | web          |
|        |          |                               |                              |                                                                                   | guest        |
|        | POST     | register                      | register.post                | App\Http\Controllers\Auth\RegisterController@register                             | web          |
|        |          |                               |                              |                                                                                   | guest        |
|        | GET|HEAD | register                      | register                     | App\Http\Controllers\Auth\RegisterController@showRegistrationForm                 | web          |
|        |          |                               |                              |                                                                                   | guest        |
|        | POST     | tokenized-login/login         | tokenized_login.login        | Imanghafoori\TokenizedLogin\Http\Controllers\TokenSenderController@loginWithToken | api          |
|        |          |                               |                              |                                                                                   | throttle:3,1 |
|        | POST     | tokenized-login/request-token | tokenized_login.requestToken | Imanghafoori\TokenizedLogin\Http\Controllers\TokenSenderController@issueToken     | api          |
|        |          |                               |                              |                                                                                   | throttle:3,1 |
+--------+----------+-------------------------------+------------------------------+-----------------------------------------------------------------------------------+--------------+`

**Comment by FelipeVeiga** [comment]
![image](https://user-images.githubusercontent.com/32652877/107836930-9dc1de80-6d7d-11eb-93ba-6688c17590d8.png)

what's is it ?

**Comment by imanghafoori1** [comment]
1. make sure you have installed it with the : composer install command and NOT composer update
2. check to see if you have laravel v8.12.3. (PHP artisan --version)
3. try to delete all the caches. (Delete files in the "bootstrap/cache" folder)

**Comment by imanghafoori1** [comment]
@FelipeVeiga 
use the latest commit and it should work. ;)
